---
apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-bootstrap
  namespace: openldap
data:
  01-base.ldif: |-
    dn: dc=example,dc=org
    objectClass: top
    objectClass: dcObject
    objectClass: organization
    o: Example Organization
    dc: example

    dn: ou=users,dc=example,dc=org
    objectClass: organizationalUnit
    ou: users

    dn: ou=groups,dc=example,dc=org
    objectClass: organizationalUnit
    ou: groups

  02-users.ldif: |-
    dn: uid=fred,ou=users,dc=example,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Fred Flintstone
    sn: Flintstone
    givenName: Fred
    uid: fred
    mail: fred@example.org
    userPassword: {MD5}VwqQv7+MfqtdxdTiaDLVsQ==

    dn: uid=wilma,ou=users,dc=example,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Wilma Flintstone
    sn: Flintstone
    givenName: Wilma
    uid: wilma
    mail: wilma@example.org
    userPassword: {MD5}Ok3ByQy+WQvuGa6VJDTwTA==
    
    dn: uid=barney,ou=users,dc=example,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Barney Rubble
    sn: Rubble
    givenName: Barney
    uid: barney
    mail: barney@example.org
    userPassword: {MD5}c9lMoJ3n0juFMnOwNcvHUg==

    dn: uid=betty,ou=users,dc=example,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Betty Rubble
    sn: Rubble
    givenName: Betty
    uid: betty
    mail: betty@example.org
    userPassword: {MD5}grBUvYP/rZts+L25jOPMLw==

    dn: uid=pebbles,ou=users,dc=example,dc=org
    objectClass: inetOrgPerson
    objectClass: organizationalPerson
    objectClass: person
    objectClass: top
    cn: Pebbles Flintstone
    sn: Flintstone
    givenName: Pebbles
    uid: pebbles
    mail: pebbles@example.org
    userPassword: {MD5}5KqOqyKW4noyc1TLsLLF0g==

  03-groups.ldif: |-
    dn: cn=infrastructure-operators,ou=groups,dc=example,dc=org
    objectClass: top
    objectClass: groupOfUniqueNames
    cn: infrastructure-operators
    uniqueMember: uid=wilma,ou=users,dc=example,dc=org

    dn: cn=application-operators,ou=groups,dc=example,dc=org
    objectClass: top
    objectClass: groupOfUniqueNames
    cn: application-operators
    uniqueMember: uid=barney,ou=users,dc=example,dc=org
    uniqueMember: uid=pebbles,ou=users,dc=example,dc=org

    dn: cn=platform-administrators,ou=groups,dc=example,dc=org
    objectClass: top
    objectClass: groupOfUniqueNames
    cn: platform-administrators
    uniqueMember: uid=betty,ou=users,dc=example,dc=org
    uniqueMember: uid=fred,ou=users,dc=example,dc=org
